from pydantic import BaseModel, Field
from typing import Optional, List

class VoiceStartRequest(BaseModel):
    session_id: str = Field(..., description="UUID of the voice session generated by Spring Boot")
    user_id: Optional[int] = Field(None, description="ID of the user running the session")
    strict_faq: bool = Field(True, description="Whether FAQ rules should be strictly enforced")

class VoiceStartResponse(BaseModel):
    session_id: str
    room_url: str
    token: str
    status: str

class VoiceStopRequest(BaseModel):
    session_id: str

class VoiceStopResponse(BaseModel):
    session_id: str
    status: str
    duration_seconds: int
    input_tokens: int
    output_tokens: int

class ChatRequest(BaseModel):
    message: str
    session_id: str

class ChatResponse(BaseModel):
    response: str
    matched_faq: bool
